"""
STEALTHWALL — config/defaults.py

SINGLE SOURCE OF TRUTH for all tuned numeric defaults (plan Section 0:
"Config consolidation"). Every module imports from this file; no hardcoded
duplicate values anywhere else in the codebase.

The Node.js middleware cannot import Python directly. Its mirrored copy lives
at middleware/express/config.json and is generated by `python3 sync_config.py`
(config/sync_to_node.py) — tests/parity asserts both copies agree, so drift
between languages fails CI instead of passing silently.

Every value below carries its plan-section reference and honest status
(picked vs empirically validated). Several defaults are picked-not-yet-
validated; they are tuned during Month 4 testing (plan Sections 3/5).
"""

# ---------------------------------------------------------------------------
# Versioning (plan Section 5: model/schema versioning + fallback-on-mismatch)
# ---------------------------------------------------------------------------

#: Version of the feature-extraction spec (docs/feature_extraction_spec.md).
#: Embedded in exported ONNX metadata and asserted by the parity CI test.
FEATURE_SPEC_VERSION = 1

#: Schema version the middleware expects when loading a model artifact.
#: On mismatch: fall back to last-known-good cached model, log CRITICAL,
#: keep serving (never hard-refuse / go down).
MODEL_SCHEMA_VERSION = 1

# ---------------------------------------------------------------------------
# Feature extraction (docs/feature_extraction_spec.md is normative)
# ---------------------------------------------------------------------------

#: Per-source-IP sliding observation window in seconds.
WINDOW_SECONDS = 60.0

#: Maximum events retained per IP window (memory bound; oldest evicted first).
WINDOW_MAX_EVENTS_PER_IP = 4096

#: Payload strings are hashed into the extractor at this truncation length.
PAYLOAD_SAMPLE_MAX_BYTES = 2048

#: Number of decimal places feature values are rounded to before being fed
#: to the classifier. Rounding happens identically in Node and Python so the
#: two runtimes produce bit-identical vectors (tests/parity enforces this).
FEATURE_ROUNDING_DECIMALS = 6

# ---------------------------------------------------------------------------
# Scoring caps (plan Section 3: "Signature-feature weight cap")
# ---------------------------------------------------------------------------

#: Maximum contribution of the payload/injection-signature feature to the
#: final blended score. It is one weighted input feature, NEVER a standalone
#: block trigger.
#: Status: PICKED default, empirically tuned in Month 4 against real
#: precision/recall sensitivity sweep (plan Sections 3, 11 Month 4, 12).
SIGNATURE_FEATURE_MAX_WEIGHT = 0.30

# ---------------------------------------------------------------------------
# Graduated response confidence tiers (plan Section 6 table)
# Score boundaries on the blended malicious-probability (0..1).
# ---------------------------------------------------------------------------

#: >= LOW: log only.
TIER_LOW_THRESHOLD = 0.30
#: >= MEDIUM: rate-limit / throttle.
TIER_MEDIUM_THRESHOLD = 0.55
#: >= HIGH: mCaptcha challenge (self-hosted).
TIER_HIGH_THRESHOLD = 0.75
#: >= VERY_HIGH: temporary IP block (hours-range TTL).
TIER_VERY_HIGH_THRESHOLD = 0.90
#: "Confirmed repeat offender" long-cooldown tier is reached via offense
#: history (see ESCALATE_TO_LONG_COOLDOWN_OFFENSES), not raw score alone.

# ---------------------------------------------------------------------------
# Block TTL tiers in seconds (plan Section 6: graduated, auto-expiring)
# ---------------------------------------------------------------------------

#: Unidentified-shared-IP provisional block lower bound (15 minutes).
PROVISIONAL_SHARED_IP_TTL_MIN_SECONDS = 15 * 60
#: Unidentified-shared-IP provisional block upper bound (30 minutes).
PROVISIONAL_SHARED_IP_TTL_MAX_SECONDS = 30 * 60
#: Default provisional TTL actually used within [MIN, MAX].
PROVISIONAL_SHARED_IP_TTL_DEFAULT_SECONDS = 20 * 60

#: Temporary IP block range: hours (low end).
TEMP_BLOCK_TTL_MIN_SECONDS = 1 * 60 * 60
#: Temporary IP block range: hours (high end).
TEMP_BLOCK_TTL_MAX_SECONDS = 4 * 60 * 60
#: Default temporary block TTL used within [MIN, MAX].
TEMP_BLOCK_TTL_DEFAULT_SECONDS = 2 * 60 * 60

#: Confirmed repeat-offender long-cooldown range: days (low end).
REPEAT_OFFENDER_TTL_MIN_SECONDS = 24 * 60 * 60
#: Confirmed repeat-offender long-cooldown range: days (high end).
REPEAT_OFFENDER_TTL_MAX_SECONDS = 72 * 60 * 60
#: Default repeat-offender block TTL used within [MIN, MAX].
REPEAT_OFFENDER_TTL_DEFAULT_SECONDS = 48 * 60 * 60

# ---------------------------------------------------------------------------
# Offense history (plan Section 6: escalation + decay)
# ---------------------------------------------------------------------------

#: Number of distinct blocks after which an IP is treated as a confirmed
#: repeat offender and escalated straight to the long-cooldown tier.
ESCALATE_TO_LONG_COOLDOWN_OFFENSES = 3

#: Returning offenders get a shortened grace period: their effective score
#: is boosted by this additive factor while history is un-decayed.
RETURNING_OFFENDER_SCORE_BOOST = 0.05

#: Offense-history decay half-life in days. History decays on a longer
#: window than any block TTL (blocks expire in days, history decays in
#: months) so recycled dynamic/residential IPs are not penalized forever.
OFFENSE_HISTORY_DECAY_HALF_LIFE_DAYS = 90

# ---------------------------------------------------------------------------
# Rate-limiting (MEDIUM graduated tier)
# ---------------------------------------------------------------------------

RATE_LIMIT_WINDOW_SECONDS = 60.0
RATE_LIMIT_MAX_REQUESTS = 20
#: Throttle delay applied per request when the limit is exceeded (seconds).
RATE_LIMIT_THROTTLE_DELAY_SECONDS = 1.0

# ---------------------------------------------------------------------------
# Adaptive scoring layer — Model 2 (plan Sections 5/6/7)
# A lightweight score-adjustment layer, NOT an online-retrained model.
# ---------------------------------------------------------------------------

#: BIDIRECTIONAL adaptation-rate cap: bounds how much more permissive AND
#: how much more aggressive the baseline may shift per hour (poisoning
#: defense in BOTH directions, plan Section 6).
MAX_BASELINE_SHIFT_PER_HOUR = 0.05

#: Cold-start floor: Model 2 may never adjust a cold-start high-confidence
#: detection (score >= this threshold) downward past the threshold itself.
COLD_START_FLOOR_THRESHOLD = TIER_HIGH_THRESHOLD

#: Learning rate of the per-IP baseline adjustment (conservative).
ADAPTIVE_BASELINE_LEARNING_RATE = 0.02

#: Audit/rollback log location for adaptive-layer AND block-engine changes
#: (whitelist edits, reconcile merges). Log-before/after state, append-only.
AUDIT_LOG_PATH = "data/audit_log.jsonl"

# ---------------------------------------------------------------------------
# Model1/Model2 drift check (plan Section 5 — detection only, NOT prevention;
# up to one month of undetected drift possible between checks)
# ---------------------------------------------------------------------------

#: Interval between drift checks.
DRIFT_CHECK_INTERVAL_DAYS = 30
#: Mean score deviation above this fraction (>10% by default) flags
#: divergence. Status: PICKED, unvalidated against real drift data.
DRIFT_SCORE_DEVIATION_THRESHOLD = 0.10

# ---------------------------------------------------------------------------
# ASN-aware blast-radius protection (plan Section 6: asn_check.py)
# ---------------------------------------------------------------------------

#: Free static IP2ASN-lite flat file source (zero-budget rule).
ASN_LIST_URL = "https://iptoasn.com/data/ip2asn-v4.tsv.gz"

#: Refresh cadence for the ASN list (in-process scheduler, NOT cron —
#: container base images often lack cron; silent-never-runs failure mode).
ASN_REFRESH_INTERVAL_HOURS = 24

#: HARD CAP on stale fallback: after this many consecutive failed refresh
#: attempts the system escalates from "log warning" to refusing further
#: ASN-gated blocking decisions (fails loud rather than serving an
#: arbitrarily stale list forever).
ASN_MAX_CONSECUTIVE_REFRESH_FAILURES = 5

#: Known cloud/proxy/CGNAT ranges get their escalation confidence reduced
#: by this multiplicative weight before blocking decisions.
ASN_REDUCED_CONFIDENCE_WEIGHT = 0.50

#: Local cache path for last-known-good ASN table (refresh-failure fallback).
ASN_CACHE_PATH = "data/ip2asn_cache.tsv"

# ---------------------------------------------------------------------------
# iptables block engine (plan Section 6)
# ---------------------------------------------------------------------------

#: Dedicated chain owned by StealthWall. Never touches built-in chains.
IPTABLES_CHAIN = "STEALTHWALL"

#: Startup check verifies iptables availability; if missing the middleware
#: FAILS LOUD (refuses start or logs critical unmissable warning) — never
#: silently runs with blocking disabled.
IPTABLES_FAIL_LOUD = True

#: Single-writer queue: one dedicated process owns ALL iptables writes;
#: other workers submit via IPC on this unix socket (concurrency fix,
#: plan Section 6 "iptables concurrency").
BLOCK_WRITER_SOCKET_PATH = "/tmp/stealthwall_block_writer.sock"

# ---------------------------------------------------------------------------
# Shared store reconcile-on-reconnect (plan Section 6: reconcile.py)
# ---------------------------------------------------------------------------

#: Writes whose timestamp skews MORE than this from the receiving
#: instance's clock are rejected outright (crude-spoof protection ONLY —
#: subtle skew kept under this bound still wins last-write-wins).
RECONCILE_MAX_CLOCK_SKEW_SECONDS = 300

#: Rejected writes are logged here, never silently dropped.
RECONCILE_REJECT_LOG_PATH = "data/reconcile_reject_log.jsonl"

#: Shared-store outage policy: fail-open (availability prioritized; local
#: iptables state acts as last-known-good fallback).
SHARED_STORE_TIMEOUT_SECONDS = 5.0

# ---------------------------------------------------------------------------
# Cloudflare CDN integration (plan Section 6: free tier only)
# ---------------------------------------------------------------------------

#: CDN push is asynchronous best-effort and NEVER gates the local block.
CF_PUSH_ASYNC = True
CF_PUSH_TIMEOUT_SECONDS = 10.0
CF_PUSH_MAX_RETRIES = 2
#: Multi-account failover: try accounts in listed order until one succeeds.
CF_ACCOUNTS_CONFIG_PATH = "config/cloudflare_accounts.json"

# ---------------------------------------------------------------------------
# mCaptcha integration (plan Section 6: self-hosted proof-of-work CAPTCHA)
# ---------------------------------------------------------------------------

MCAPTCHA_DEFAULT_TTL_SECONDS = 1800
MCAPTCHA_DIFFICULTY_FACTOR = 50000
#: mCaptcha needs its own worker process + storage — scheduled as real
#: subsystem work (Month 2), not assumed zero-effort.
MCAPTCHA_INTERNAL_SITE_KEY = "stealthwall-internal"

# ---------------------------------------------------------------------------
# Whitelist security (plan Section 6: "Whitelist as an attack surface")
# ---------------------------------------------------------------------------

#: Whitelist edits REQUIRE re-authentication (password re-entry) on the same
#: admin session; every change logged with timestamp + actor. Known limit:
#: weak against a fully compromised admin account (no MFA in scope).
WHITELIST_REQUIRE_REAUTH = True
WHITELIST_REAUTH_MAX_AGE_SECONDS = 120

#: Dashboard (plan Section 6: gated behind app-admin auth)
# ---------------------------------------------------------------------------

DASHBOARD_SESSION_COOKIE = "stealthwall_admin_session"
DASHBOARD_FEED_POLL_SECONDS = 2

#: Path to the target app's SQLite DB — the dashboard validates admin
#: sessions DIRECTLY against it (auth reuse is the design; no second
#: auth system).
TARGET_DB_PATH = "data/self_hosted_target/target.db"

# ---------------------------------------------------------------------------
# Parity testing (plan Section 5: cross-implementation CI gate)
# ---------------------------------------------------------------------------

#: Float comparison tolerance when asserting Node/Python vector equality
#: (both sides round to FEATURE_ROUNDING_DECIMALS first, so exact equality
#: is expected; tolerance exists only to absorb JSON float serialization).
PARITY_FLOAT_EPSILON = 1e-9


def clamp(value: float, low: float, high: float) -> float:
    """Shared clamp helper (used by TTL pickers and score blending)."""
    return max(low, min(high, value))


def ttl_for_provisional_shared_ip() -> int:
    return PROVISIONAL_SHARED_IP_TTL_DEFAULT_SECONDS


def ttl_for_temp_block(offenses: int) -> int:
    """Escalating temp-block TTL inside the hours range based on offenses."""
    span = TEMP_BLOCK_TTL_MAX_SECONDS - TEMP_BLOCK_TTL_MIN_SECONDS
    step = span / max(1, (ESCALATE_TO_LONG_COOLDOWN_OFFENSES - 1))
    offset = clamp((offenses - 1) * step, 0, span)
    return int(TEMP_BLOCK_TTL_MIN_SECONDS + offset)


def ttl_for_repeat_offender(offenses: int) -> int:
    """Long-cooldown TTL inside the days range; grows with repeat count."""
    span = REPEAT_OFFENDER_TTL_MAX_SECONDS - REPEAT_OFFENDER_TTL_MIN_SECONDS
    extra_blocks = max(0, offenses - ESCALATE_TO_LONG_COOLDOWN_OFFENSES)
    offset = min(span, extra_blocks * (span // 4 if span >= 4 else span))
    return int(REPEAT_OFFENDER_TTL_MIN_SECONDS + offset)


def response_tier(score: float) -> str:
    """Map a blended score to its graduated-response tier name."""
    if score >= TIER_VERY_HIGH_THRESHOLD:
        return "very_high"
    if score >= TIER_HIGH_THRESHOLD:
        return "high"
    if score >= TIER_MEDIUM_THRESHOLD:
        return "medium"
    if score >= TIER_LOW_THRESHOLD:
        return "low"
    return "none"


ALL_DEFAULTS = {
    name: value
    for name, value in sorted(globals().items())
    if name.isupper() and isinstance(value, (int, float, str, bool))
}
